algorithm: fixmatch_if
save_dir: ./saved_models/usb_cv/
save_name: fixmatchif_bus_878_signedadd_1
resume: False
load_path: ./saved_models/usb_cv/fixmatchif_bus_878_signedadd_1/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 50
num_train_iter: 5500
num_log_iter: 110
num_eval_iter: 110
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 220
num_labels: 878
uratio: 30
ema_m: 0.999
hard_label: True
T: 0.5
p_cutoff: 0.9
ifrank_loss_weight: 1.0
k: 8
num_references: 4
corrT: 0.1
combine: 'signedadd'
if_lambda: 1.0
csim_lambda: 1.0
use_strong_if: False
img_size: 224
crop_ratio: 0.875
optim: SGD
lr: 0.0046875
sched: linear
lr_drop_iter: 1650 3300 4950
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 1.0
use_cat: True
net: resnet18
net_from_name: False
data_dir: ../uda_data
dataset: bus
train_sampler: RandomSampler
num_classes: 2
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10082
dist_backend: nccl
gpu: None
use_pretrain: False
lpath: ../data_split/28/labeled_images_20_9.pth
ulpath: ../data_split/28/unlabeled_images_80_9.pth
pretrain_path: https://download.pytorch.org/models/resnet18-5c106cde.pth
