algorithm: supervised
save_dir: ./saved_models/usb_cv/
save_name: supervised_tn5000_28_0
resume: False
load_path: ./saved_models/usb_cv/supervised_tn5000_28_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 50
num_train_iter: 4400
num_log_iter: 88
num_eval_iter: 88
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 176
num_labels: 700
label_ratio: 0.2
fold: 1
uratio: 1
ema_m: 0.0
best_metric: balanced_acc
img_size: 224
crop_ratio: 0.875
optim: SGD
lr: 0.0046875
sched: linear
lr_drop_iter: 1320 2640 3960
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: resnet18
net_from_name: False
data_dir: ../uda_data/TN5000
dataset: tn5000
train_sampler: RandomSampler
num_classes: 2
num_workers: 4
seed: 0
split_seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10019
dist_backend: nccl
gpu: None
use_pretrain: False
pretrain_path: https://download.pytorch.org/models/resnet18-5c106cde.pth
