algorithm: freematch
save_dir: ./saved_models/usb_cv/
save_name: freematch_bus_878_0
resume: True
load_path: ./saved_models/usb_cv//freematch_bus_878_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 50
num_train_iter: 5500
num_log_iter: 1
num_eval_iter: 110
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 220
num_labels: 878
uratio: 30 #1
ema_m: 0.0 #0.999
hard_label: True
T: 0.5
ema_p: 0.999
ent_loss_ratio: 0.001 # weight of entropy loss
img_size: 224
crop_ratio: 0.875
optim: SGD #AdamW #SGD
lr: 0.009375  #0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: resnet18 #vit_small_patch2_32
net_from_name: False
data_dir: ../uda_data
dataset: bus
train_sampler: RandomSampler
num_classes: 2
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10081
dist_backend: nccl
gpu: None
use_pretrain: False #True
lpath: ../data_split/28/labeled_images_20_9.pth
ulpath: ../data_split/28/unlabeled_images_80_9.pth
pretrain_path: https://download.pytorch.org/models/resnet18-5c106cde.pth 
#https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch2_32_mlp_im_1k_32.pth